apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
  name: nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  strategy: {}
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - image: zarakmughal/nodejs-starter:1.0
          name: nodejs-starter
status: {}